### ISSUE TITLE
Issues in the newest version

### ISSUE THREAD

**Issue by buzzard10** [domainzero/bookstack-dark-theme#1]
Hello. Great idea for dark theme, but i have issue with install on BookStack v0.19.0

**Comment by domainzero** [comment]
Whoa, didn't even see this issue.

Yeah, v0.19.0 definitely changed a lot of the styling and I haven't had time to tackle building a new dark theme. 

I'll work on it when I find some time.

**Comment by domainzero** [comment]
@emillod new changes pushed. should be updated for v.0.19.0 now.
