### ISSUE TITLE
Move to official org?

### ISSUE THREAD

**Issue by zenorocha** [domainzero/bookstack-dark-theme#15]
Hey @domainzero,

This is Zeno, creator of Dracula. I just this found repo, good job on that!

I'm wondering if you would like to have this become an official theme in our [Dracula organization](https://github.com/dracula)?

Let me know what you think.

**Comment by domainzero** [comment]
Hey @zenorocha!

Sure! Send me an invite and I'll get the template filled out.

**Comment by zenorocha** [comment]
Invitation sent! Thanks @domainzero ;)

**Comment by zenorocha** [comment]
Friendly ping ;)

**Comment by domainzero** [comment]
Hey! Sorry, been crazy busy lately and haven't had time to get the template all filled out. Should be able to do it this weekend. 

Thanks for the reminder, I honestly needed it.

**Comment by domainzero** [comment]
An official dark mode theme has been created by the app author.
I'm planning to retool this stylesheet for use with the new theme, but this will delay getting this brought in to the dracula org.

**Comment by thechickenmoo** [comment]
> An official dark mode theme has been created by the app author.
> I'm planning to retool this stylesheet for use with the new theme, but this will delay getting this brought in to the dracula org.

Damn. I was trying to figure why it wouldn't fully apply after updating.

Well. Know there are those still interested :D

**Comment by domainzero** [comment]
@thechickenmoo Hey! I updated this recently. Can you give a try and let me know if it's still busted? Use both the stylesheet itself and the snippet of CSS in the readme.

**Comment by domainzero** [comment]
@thechickenmoo opening a new issue #18

**Comment by zenorocha** [comment]
@domainzero how are things going? Just checking to see if you're still looking interested in this, no pressure :)
