### ISSUE TITLE
transparency

### ISSUE THREAD

**Issue by xiaoveiti** [domainzero/bookstack-dark-theme#17]
I love the theme. Thanks for the work! But somehow the transparency doesn't work for me. The navigation bar above is not transparent and therefore looks a bit strange - haha

I'm using nginx and already cleared the cache. Any idea how to solve this?

**Comment by domainzero** [comment]
Do you have a screenshot handy?
What version of Bookstack are you on?

**Comment by domainzero** [comment]
Should be fixed in 20ac869

**Comment by xiaoveiti** [comment]
thanks for the quick reply and the quick fix! It's working now!
