### ISSUE TITLE
Style issues with new theme

### ISSUE THREAD

**Issue by domainzero** [domainzero/bookstack-dark-theme#18]
> An official dark mode theme has been created by the app author.
> I'm planning to retool this stylesheet for use with the new theme, but this will delay getting this brought in to the dracula org.

Damn. I was trying to figure why it wouldn't fully apply after updating.

Well. Know there are those still interested :D

_Originally posted by @thechickenmoo in https://github.com/domainzero/bookstack-dark-theme/issues/15#issuecomment-708134693_

**Comment by domainzero** [comment]
I recently updated this and things look ok on my end.
What version of Bookstack are you on?
Have you placed the snippet of CSS that's in the readme into your Custom HTML head settings?

**Comment by thechickenmoo** [comment]
Embarrassingly I didn't turn on "dark mode" after making the changes. Haha
I expected the changes to take over the default white background and didn't even notice the "dark mode" button. 

BookStack v0.30.3
