### ISSUE TITLE
WYSIWYG editor white text on white background

### ISSUE THREAD

**Issue by voidstarr** [domainzero/bookstack-dark-theme#4]
![bookstack-dark](https://user-images.githubusercontent.com/3334013/37238209-82d19d20-23d6-11e8-8716-4f6fc3aa4139.PNG)

I've been digging into the css in an attempt to find a solution, but my understanding is limited in this area. I very much enjoy the theme, but I can't use it without being able to use the editor.

**Comment by domainzero** [comment]
@voidstarr 
Whoa! Sorry this is like three months late.
I didn't get alerted for this!

I noticed you fixed it in your fork - wanna submit a pull request and I can merge it it?

**Comment by domainzero** [comment]
Nevermind, you totally did. Merged!

**Comment by sigmap** [comment]
I still see white text on a white background in the wysiwyg. Am I missing something?

**Comment by domainzero** [comment]
There might have been a change to the wysiwyg editor that I missed. I'll
check it today.

**Comment by bjornlljohansen** [comment]
Hi, does this fix also solve the white backgroud on the code block editor? I've tried updating both bookstack and this css sheet to the newest version, without any luck. As a quick and dirty fix I've added:
`.popup-body {
  background-color: #282a36;}
`
on line 21 of dark-theme.css , but I have no idea what side effect this might have as I've just gotten started with bookstack

**Comment by domainzero** [comment]
Hey @bjornlljohansen 
The code block editor actually uses CodeMirror, which is skinnable through a different means.

Add this to your Custom HTML Head content:
```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/dracula.min.css"/>
<script>window.codeTheme='dracula';</script>
```
and it should be fixed.

Here's what it looks like on my instance:
![image](https://user-images.githubusercontent.com/7740725/51549597-52ec6b80-1e30-11e9-93a0-e3d182d9e7a5.png)

**Comment by bjornlljohansen** [comment]
I already have the dracula style sheet loaded, but if I understand correctly, it will only theme the display of the code block, and not the editor?

see example image:
![2019-01-22](https://user-images.githubusercontent.com/8566135/51552734-869bb580-1e71-11e9-8969-b37607c344c8.png)

**Comment by domainzero** [comment]
My bad! We were totally talking about different things!

That's totally broken. I'll push a change for this when I get time today.

**Comment by domainzero** [comment]
Should be fixed now.
![image](https://user-images.githubusercontent.com/7740725/51561430-d6b45100-1e4c-11e9-92a3-ce04886759e0.png)

**Comment by bjornlljohansen** [comment]
Looks really nice :+1:

You might note the contrast of the OK button for your next release, it might be hard to read on some screens :wink:
