### ISSUE TITLE
Styling in 0.24.1

### ISSUE THREAD

**Issue by sigmap** [domainzero/bookstack-dark-theme#6]
The editor and preview when using the markdown editor is styled differently from your screencaps.
It might be because I'm using the latest stable.
![screenshot](https://i.imgur.com/j6dMhCL.png)

**Comment by domainzero** [comment]
Ahhh, figures that I would leave out an important thing in the documentation.
The left hand pane is actually a Codemirror theme that is handled outside of the rest of the restyling.

Drop this inside the "Custom HTML head content" box on the settings page:
```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/dracula.min.css"/>
<script>window.codeTheme='dracula';</script>
```
This'll load the Codemirror theme and restyle the left hand pane.

I'll update the documentation. Thanks!

**Comment by domainzero** [comment]
Hey @sigmap 

Just checking in to see if that fixed your problem.

**Comment by sigmap** [comment]
It fixed my issue. Sorry for the late reply.
